---
- hosts: remote_vmss_env
  become: True
  tasks:
    - name: Install nginx package
      apt: name=nginx state=present update_cache=yes
    - name: systemctl enable nginx
      systemd:
        name: nginx
        enabled: yes

