---
- hosts: remote_vmss_env
  become: True
  tasks:
    - name: Install nginx package
      apt: name=nginx state=present update_cache=yes
    - name: systemctl enable nginx
      systemd:
        name: nginx
        enabled: yes
    - name: availability check for http service
      wait_for:
        port: 80
        delay: 1
        timeout: 5
        msg: "Timeout waiting for 80 to respond"
      register: port_check
      ignore_errors: yes

